# Generated by cstruct-stubgen
from collections.abc import Callable
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_exfat(__cs__.cstruct):
    BOOT_SIGNATURE: Literal[43605] = ...
    EXBOOT_SIGNATURE: Literal[2857697280] = ...
    STR_EXFAT: Literal["EXFAT   "] = ...
    EXFAT_MAX_FILE_LEN: Literal[255] = ...
    VOLUME_DIRTY: Literal[2] = ...
    MEDIA_FAILURE: Literal[4] = ...
    EXFAT_EOF_CLUSTER: Literal[4294967295] = ...
    EXFAT_BAD_CLUSTER: Literal[4294967287] = ...
    EXFAT_FREE_CLUSTER: Literal[0] = ...
    EXFAT_RESERVED_CLUSTERS: Literal[2] = ...
    EXFAT_FIRST_CLUSTER: Literal[2] = ...
    ALLOC_POSSIBLE: Literal[1] = ...
    ALLOC_FAT_CHAIN: Literal[1] = ...
    ALLOC_NO_FAT_CHAIN: Literal[3] = ...
    DENTRY_SIZE: Literal[32] = ...
    DENTRY_SIZE_BITS: Literal[5] = ...
    MAX_EXFAT_DENTRIES: Literal[8388608] = ...
    IS_EXFAT_DELETED: Callable[[int], bool] = ...
    EXFAT_UNUSED: Literal[0] = ...
    EXFAT_DELETE: Literal[-129] = ...
    EXFAT_INVAL: Literal[128] = ...
    EXFAT_BITMAP: Literal[129] = ...
    EXFAT_UPCASE: Literal[130] = ...
    EXFAT_VOLUME: Literal[131] = ...
    EXFAT_FILE: Literal[133] = ...
    EXFAT_GUID: Literal[160] = ...
    EXFAT_PADDING: Literal[161] = ...
    EXFAT_ACLTAB: Literal[162] = ...
    EXFAT_STREAM: Literal[192] = ...
    EXFAT_NAME: Literal[193] = ...
    EXFAT_ACL: Literal[194] = ...
    EXFAT_VENDOR_EXT: Literal[224] = ...
    EXFAT_VENDOR_ALLOC: Literal[225] = ...
    CS_DIR_ENTRY: Literal[0] = ...
    CS_BOOT_SECTOR: Literal[1] = ...
    CS_DEFAULT: Literal[2] = ...
    EXFAT_ATTR_READONLY: Literal[1] = ...
    EXFAT_ATTR_HIDDEN: Literal[2] = ...
    EXFAT_ATTR_SYSTEM: Literal[4] = ...
    EXFAT_ATTR_VOLUME: Literal[8] = ...
    EXFAT_ATTR_SUBDIR: Literal[16] = ...
    EXFAT_ATTR_ARCHIVE: Literal[32] = ...
    EXFAT_ATTR_RWMASK: Literal[62] = ...
    BOOTSEC_JUMP_BOOT_LEN: Literal[3] = ...
    BOOTSEC_FS_NAME_LEN: Literal[8] = ...
    BOOTSEC_OLDBPB_LEN: Literal[53] = ...
    EXFAT_FILE_NAME_LEN: Literal[15] = ...
    EXFAT_TZ_VALID: Literal[128] = ...
    EXFAT_MIN_TIMESTAMP_SECS: Literal[315532800] = ...
    EXFAT_MAX_TIMESTAMP_SECS: Literal[4354819199] = ...
    class boot_sector(__cs__.Structure):
        jmp_boot: __cs__.Array[_c_exfat.uint8]
        fs_name: __cs__.Array[_c_exfat.uint8]
        must_be_zero: __cs__.Array[_c_exfat.uint8]
        partition_offset: _c_exfat.uint64
        vol_length: _c_exfat.uint64
        fat_offset: _c_exfat.uint32
        fat_length: _c_exfat.uint32
        clu_offset: _c_exfat.uint32
        clu_count: _c_exfat.uint32
        root_cluster: _c_exfat.uint32
        vol_serial: _c_exfat.uint32
        fs_revision: __cs__.Array[_c_exfat.uint8]
        vol_flags: _c_exfat.uint16
        sect_size_bits: _c_exfat.uint8
        sect_per_clus_bits: _c_exfat.uint8
        num_fats: _c_exfat.uint8
        drv_sel: _c_exfat.uint8
        percent_in_use: _c_exfat.uint8
        reserved: __cs__.Array[_c_exfat.uint8]
        boot_code: __cs__.Array[_c_exfat.uint8]
        signature: _c_exfat.uint16
        @overload
        def __init__(
            self,
            jmp_boot: __cs__.Array[_c_exfat.uint8] | None = ...,
            fs_name: __cs__.Array[_c_exfat.uint8] | None = ...,
            must_be_zero: __cs__.Array[_c_exfat.uint8] | None = ...,
            partition_offset: _c_exfat.uint64 | None = ...,
            vol_length: _c_exfat.uint64 | None = ...,
            fat_offset: _c_exfat.uint32 | None = ...,
            fat_length: _c_exfat.uint32 | None = ...,
            clu_offset: _c_exfat.uint32 | None = ...,
            clu_count: _c_exfat.uint32 | None = ...,
            root_cluster: _c_exfat.uint32 | None = ...,
            vol_serial: _c_exfat.uint32 | None = ...,
            fs_revision: __cs__.Array[_c_exfat.uint8] | None = ...,
            vol_flags: _c_exfat.uint16 | None = ...,
            sect_size_bits: _c_exfat.uint8 | None = ...,
            sect_per_clus_bits: _c_exfat.uint8 | None = ...,
            num_fats: _c_exfat.uint8 | None = ...,
            drv_sel: _c_exfat.uint8 | None = ...,
            percent_in_use: _c_exfat.uint8 | None = ...,
            reserved: __cs__.Array[_c_exfat.uint8] | None = ...,
            boot_code: __cs__.Array[_c_exfat.uint8] | None = ...,
            signature: _c_exfat.uint16 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class exfat_dentry(__cs__.Structure):
        type: _c_exfat.uint8
        class __anonymous_0__(__cs__.Structure):
            char_count: _c_exfat.uint8
            vol_label: __cs__.CharArray
            reserved2: __cs__.Array[_c_exfat.uint8]
            @overload
            def __init__(
                self,
                char_count: _c_exfat.uint8 | None = ...,
                vol_label: __cs__.CharArray | None = ...,
                reserved2: __cs__.Array[_c_exfat.uint8] | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        volume: __anonymous_0__
        class __anonymous_1__(__cs__.Structure):
            num_ext: _c_exfat.uint8
            checksum: _c_exfat.uint16
            attr: _c_exfat.uint16
            reserved1: _c_exfat.uint16
            create_time: _c_exfat.uint16
            create_date: _c_exfat.uint16
            modify_time: _c_exfat.uint16
            modify_date: _c_exfat.uint16
            access_time: _c_exfat.uint16
            access_date: _c_exfat.uint16
            create_time_cs: _c_exfat.uint8
            modify_time_cs: _c_exfat.uint8
            create_tz: _c_exfat.uint8
            modify_tz: _c_exfat.uint8
            access_tz: _c_exfat.uint8
            reserved2: __cs__.Array[_c_exfat.uint8]
            @overload
            def __init__(
                self,
                num_ext: _c_exfat.uint8 | None = ...,
                checksum: _c_exfat.uint16 | None = ...,
                attr: _c_exfat.uint16 | None = ...,
                reserved1: _c_exfat.uint16 | None = ...,
                create_time: _c_exfat.uint16 | None = ...,
                create_date: _c_exfat.uint16 | None = ...,
                modify_time: _c_exfat.uint16 | None = ...,
                modify_date: _c_exfat.uint16 | None = ...,
                access_time: _c_exfat.uint16 | None = ...,
                access_date: _c_exfat.uint16 | None = ...,
                create_time_cs: _c_exfat.uint8 | None = ...,
                modify_time_cs: _c_exfat.uint8 | None = ...,
                create_tz: _c_exfat.uint8 | None = ...,
                modify_tz: _c_exfat.uint8 | None = ...,
                access_tz: _c_exfat.uint8 | None = ...,
                reserved2: __cs__.Array[_c_exfat.uint8] | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        file: __anonymous_1__
        class __anonymous_2__(__cs__.Structure):
            flags: _c_exfat.uint8
            reserved1: _c_exfat.uint8
            name_len: _c_exfat.uint8
            name_hash: _c_exfat.uint16
            reserved2: _c_exfat.uint16
            valid_size: _c_exfat.uint64
            reserved3: _c_exfat.uint32
            start_clu: _c_exfat.uint32
            size: _c_exfat.uint64
            @overload
            def __init__(
                self,
                flags: _c_exfat.uint8 | None = ...,
                reserved1: _c_exfat.uint8 | None = ...,
                name_len: _c_exfat.uint8 | None = ...,
                name_hash: _c_exfat.uint16 | None = ...,
                reserved2: _c_exfat.uint16 | None = ...,
                valid_size: _c_exfat.uint64 | None = ...,
                reserved3: _c_exfat.uint32 | None = ...,
                start_clu: _c_exfat.uint32 | None = ...,
                size: _c_exfat.uint64 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        stream: __anonymous_2__
        class __anonymous_3__(__cs__.Structure):
            flags: _c_exfat.uint8
            unicode_0_14: __cs__.Array[_c_exfat.uint16]
            @overload
            def __init__(
                self, flags: _c_exfat.uint8 | None = ..., unicode_0_14: __cs__.Array[_c_exfat.uint16] | None = ...
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        name: __anonymous_3__
        class __anonymous_4__(__cs__.Structure):
            flags: _c_exfat.uint8
            reserved: __cs__.Array[_c_exfat.uint8]
            start_clu: _c_exfat.uint32
            size: _c_exfat.uint64
            @overload
            def __init__(
                self,
                flags: _c_exfat.uint8 | None = ...,
                reserved: __cs__.Array[_c_exfat.uint8] | None = ...,
                start_clu: _c_exfat.uint32 | None = ...,
                size: _c_exfat.uint64 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        bitmap: __anonymous_4__
        class __anonymous_5__(__cs__.Structure):
            reserved1: __cs__.Array[_c_exfat.uint8]
            checksum: _c_exfat.uint32
            reserved2: __cs__.Array[_c_exfat.uint8]
            start_clu: _c_exfat.uint32
            size: _c_exfat.uint64
            @overload
            def __init__(
                self,
                reserved1: __cs__.Array[_c_exfat.uint8] | None = ...,
                checksum: _c_exfat.uint32 | None = ...,
                reserved2: __cs__.Array[_c_exfat.uint8] | None = ...,
                start_clu: _c_exfat.uint32 | None = ...,
                size: _c_exfat.uint64 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        upcase: __anonymous_5__
        class __anonymous_6__(__cs__.Structure):
            flags: _c_exfat.uint8
            vendor_guid: __cs__.Array[_c_exfat.uint8]
            vendor_defined: __cs__.Array[_c_exfat.uint8]
            @overload
            def __init__(
                self,
                flags: _c_exfat.uint8 | None = ...,
                vendor_guid: __cs__.Array[_c_exfat.uint8] | None = ...,
                vendor_defined: __cs__.Array[_c_exfat.uint8] | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        vendor_ext: __anonymous_6__
        class __anonymous_7__(__cs__.Structure):
            flags: _c_exfat.uint8
            vendor_guid: __cs__.Array[_c_exfat.uint8]
            vendor_defined: __cs__.Array[_c_exfat.uint8]
            start_clu: _c_exfat.uint32
            size: _c_exfat.uint64
            @overload
            def __init__(
                self,
                flags: _c_exfat.uint8 | None = ...,
                vendor_guid: __cs__.Array[_c_exfat.uint8] | None = ...,
                vendor_defined: __cs__.Array[_c_exfat.uint8] | None = ...,
                start_clu: _c_exfat.uint32 | None = ...,
                size: _c_exfat.uint64 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        vendor_alloc: __anonymous_7__
        class __anonymous_8__(__cs__.Structure):
            flags: _c_exfat.uint8
            custom_defined: __cs__.Array[_c_exfat.uint8]
            start_clu: _c_exfat.uint32
            size: _c_exfat.uint64
            @overload
            def __init__(
                self,
                flags: _c_exfat.uint8 | None = ...,
                custom_defined: __cs__.Array[_c_exfat.uint8] | None = ...,
                start_clu: _c_exfat.uint32 | None = ...,
                size: _c_exfat.uint64 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        generic_secondary: __anonymous_8__
        @overload
        def __init__(
            self,
            type: _c_exfat.uint8 | None = ...,
            volume: __anonymous_0__ | None = ...,
            file: __anonymous_1__ | None = ...,
            stream: __anonymous_2__ | None = ...,
            name: __anonymous_3__ | None = ...,
            bitmap: __anonymous_4__ | None = ...,
            upcase: __anonymous_5__ | None = ...,
            vendor_ext: __anonymous_6__ | None = ...,
            vendor_alloc: __anonymous_7__ | None = ...,
            generic_secondary: __anonymous_8__ | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_exfat` is an instance of `_c_exfat`, but then we can't use it in type hints
c_exfat: TypeAlias = _c_exfat
