# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_exfat(__cs__.cstruct):
    EXFAT_DIRENT_SIZE: Literal[32] = ...
    EXFAT_DIRENT_TYPE_END: Literal[0] = ...
    EXFAT_DIRENT_TYPE_UNUSED: Literal[128] = ...
    EXFAT_DIRENT_TYPE_ALLOC_BITMAP: Literal[129] = ...
    EXFAT_DIRENT_TYPE_UPCASE: Literal[130] = ...
    EXFAT_DIRENT_TYPE_VOLUME_LABEL: Literal[131] = ...
    EXFAT_DIRENT_TYPE_FILE: Literal[133] = ...
    EXFAT_DIRENT_TYPE_VOLUME_GUID: Literal[160] = ...
    EXFAT_DIRENT_TYPE_TEXFAT_PADDING: Literal[161] = ...
    EXFAT_DIRENT_TYPE_STREAM_EXT: Literal[192] = ...
    EXFAT_DIRENT_TYPE_FILE_NAME: Literal[193] = ...
    EXFAT_DIRENT_TYPE_VENDOR_EXT: Literal[224] = ...
    EXFAT_DIRENT_TYPE_VENDOR_ALLOC: Literal[225] = ...
    EXFAT_DIRENT_FLAG_ALLOC_POSSIBLE: Literal[1] = ...
    EXFAT_DIRENT_FLAG_NO_FAT_CHAIN: Literal[2] = ...
    class _BOOT_SECTOR(__cs__.Structure):
        JumpBoot: __cs__.Array[_c_exfat.uint8]
        FileSystemName: __cs__.Array[_c_exfat.uint8]
        MustBeZero: __cs__.Array[_c_exfat.uint8]
        PartitionOffset: _c_exfat.uint64
        VolumeLength: _c_exfat.uint64
        FatOffset: _c_exfat.uint32
        FatLength: _c_exfat.uint32
        ClusterHeapOffset: _c_exfat.uint32
        ClusterCount: _c_exfat.uint32
        FirstClusterOfRootDirectory: _c_exfat.uint32
        VolumeSerialNumber: _c_exfat.uint32
        FileSystemRevision: _c_exfat.uint16
        VolumeFlags: _c_exfat.uint16
        BytesPerSectorShift: _c_exfat.uint8
        SectorsPerClusterShift: _c_exfat.uint8
        NumberOfFats: _c_exfat.uint8
        DriveSelect: _c_exfat.uint8
        PercentInUse: _c_exfat.uint8
        Reserved: __cs__.Array[_c_exfat.uint8]
        BootCode: __cs__.Array[_c_exfat.uint8]
        BootSignature: _c_exfat.uint16
        @overload
        def __init__(
            self,
            JumpBoot: __cs__.Array[_c_exfat.uint8] | None = ...,
            FileSystemName: __cs__.Array[_c_exfat.uint8] | None = ...,
            MustBeZero: __cs__.Array[_c_exfat.uint8] | None = ...,
            PartitionOffset: _c_exfat.uint64 | None = ...,
            VolumeLength: _c_exfat.uint64 | None = ...,
            FatOffset: _c_exfat.uint32 | None = ...,
            FatLength: _c_exfat.uint32 | None = ...,
            ClusterHeapOffset: _c_exfat.uint32 | None = ...,
            ClusterCount: _c_exfat.uint32 | None = ...,
            FirstClusterOfRootDirectory: _c_exfat.uint32 | None = ...,
            VolumeSerialNumber: _c_exfat.uint32 | None = ...,
            FileSystemRevision: _c_exfat.uint16 | None = ...,
            VolumeFlags: _c_exfat.uint16 | None = ...,
            BytesPerSectorShift: _c_exfat.uint8 | None = ...,
            SectorsPerClusterShift: _c_exfat.uint8 | None = ...,
            NumberOfFats: _c_exfat.uint8 | None = ...,
            DriveSelect: _c_exfat.uint8 | None = ...,
            PercentInUse: _c_exfat.uint8 | None = ...,
            Reserved: __cs__.Array[_c_exfat.uint8] | None = ...,
            BootCode: __cs__.Array[_c_exfat.uint8] | None = ...,
            BootSignature: _c_exfat.uint16 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    BOOT_SECTOR: TypeAlias = _BOOT_SECTOR
    class _DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        CustomDefined: __cs__.Array[_c_exfat.uint8]
        @overload
        def __init__(
            self, EntryType: _c_exfat.uint8 | None = ..., CustomDefined: __cs__.Array[_c_exfat.uint8] | None = ...
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    DIRENT: TypeAlias = _DIRENT
    class _GENERIC_PRIMARY_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        SecondaryCount: _c_exfat.uint8
        SetChecksum: _c_exfat.uint16
        GeneralPrimaryFlags: _c_exfat.uint16
        CustomDefined: __cs__.Array[_c_exfat.uint8]
        FirstCluster: _c_exfat.uint32
        DataLength: _c_exfat.uint64
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            SecondaryCount: _c_exfat.uint8 | None = ...,
            SetChecksum: _c_exfat.uint16 | None = ...,
            GeneralPrimaryFlags: _c_exfat.uint16 | None = ...,
            CustomDefined: __cs__.Array[_c_exfat.uint8] | None = ...,
            FirstCluster: _c_exfat.uint32 | None = ...,
            DataLength: _c_exfat.uint64 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    GENERIC_PRIMARY_DIRENT: TypeAlias = _GENERIC_PRIMARY_DIRENT
    class _GENERIC_SECONDARY_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        GeneralSecondaryFlags: _c_exfat.uint8
        CustomDefined: __cs__.Array[_c_exfat.uint8]
        FirstCluster: _c_exfat.uint32
        DataLength: _c_exfat.uint64
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            GeneralSecondaryFlags: _c_exfat.uint8 | None = ...,
            CustomDefined: __cs__.Array[_c_exfat.uint8] | None = ...,
            FirstCluster: _c_exfat.uint32 | None = ...,
            DataLength: _c_exfat.uint64 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    GENERIC_SECONDARY_DIRENT: TypeAlias = _GENERIC_SECONDARY_DIRENT
    class _ALLOC_BITMAP_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        BitmapFlags: _c_exfat.uint8
        Reserved: __cs__.Array[_c_exfat.uint8]
        FirstCluster: _c_exfat.uint32
        DataLength: _c_exfat.uint64
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            BitmapFlags: _c_exfat.uint8 | None = ...,
            Reserved: __cs__.Array[_c_exfat.uint8] | None = ...,
            FirstCluster: _c_exfat.uint32 | None = ...,
            DataLength: _c_exfat.uint64 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    ALLOC_BITMAP_DIRENT: TypeAlias = _ALLOC_BITMAP_DIRENT
    class _UPCASE_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        Reserved1: __cs__.Array[_c_exfat.uint8]
        TableChecksum: _c_exfat.uint32
        Reserved2: __cs__.Array[_c_exfat.uint8]
        FirstCluster: _c_exfat.uint32
        DataLength: _c_exfat.uint64
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            Reserved1: __cs__.Array[_c_exfat.uint8] | None = ...,
            TableChecksum: _c_exfat.uint32 | None = ...,
            Reserved2: __cs__.Array[_c_exfat.uint8] | None = ...,
            FirstCluster: _c_exfat.uint32 | None = ...,
            DataLength: _c_exfat.uint64 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    UPCASE_DIRENT: TypeAlias = _UPCASE_DIRENT
    class _VOLUME_LABEL_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        CharacterCount: _c_exfat.uint8
        VolumeLabel: __cs__.Array[_c_exfat.uint8]
        Reserved: __cs__.Array[_c_exfat.uint8]
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            CharacterCount: _c_exfat.uint8 | None = ...,
            VolumeLabel: __cs__.Array[_c_exfat.uint8] | None = ...,
            Reserved: __cs__.Array[_c_exfat.uint8] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    VOLUME_LABEL_DIRENT: TypeAlias = _VOLUME_LABEL_DIRENT
    class _FILE_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        SecondaryCount: _c_exfat.uint8
        SetChecksum: _c_exfat.uint16
        FileAttributes: _c_exfat.uint16
        Reserved1: __cs__.Array[_c_exfat.uint8]
        CreateTimestamp: _c_exfat.uint32
        LastModifiedTimestamp: _c_exfat.uint32
        LastAccessedTimestamp: _c_exfat.uint32
        Create10msIncrement: _c_exfat.uint8
        LastModified10msIncrement: _c_exfat.uint8
        CreateUtcOffset: _c_exfat.uint8
        LastModifiedUtcOffset: _c_exfat.uint8
        LastAccessedUtcOffset: _c_exfat.uint8
        Reserved2: __cs__.Array[_c_exfat.uint8]
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            SecondaryCount: _c_exfat.uint8 | None = ...,
            SetChecksum: _c_exfat.uint16 | None = ...,
            FileAttributes: _c_exfat.uint16 | None = ...,
            Reserved1: __cs__.Array[_c_exfat.uint8] | None = ...,
            CreateTimestamp: _c_exfat.uint32 | None = ...,
            LastModifiedTimestamp: _c_exfat.uint32 | None = ...,
            LastAccessedTimestamp: _c_exfat.uint32 | None = ...,
            Create10msIncrement: _c_exfat.uint8 | None = ...,
            LastModified10msIncrement: _c_exfat.uint8 | None = ...,
            CreateUtcOffset: _c_exfat.uint8 | None = ...,
            LastModifiedUtcOffset: _c_exfat.uint8 | None = ...,
            LastAccessedUtcOffset: _c_exfat.uint8 | None = ...,
            Reserved2: __cs__.Array[_c_exfat.uint8] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    FILE_DIRENT: TypeAlias = _FILE_DIRENT
    class _VOLUME_GUID_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        SecondaryCount: _c_exfat.uint8
        SetChecksum: _c_exfat.uint16
        GeneralPrimaryFlags: _c_exfat.uint16
        VolumeGuid: __cs__.Array[_c_exfat.uint8]
        Reserved: __cs__.Array[_c_exfat.uint8]
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            SecondaryCount: _c_exfat.uint8 | None = ...,
            SetChecksum: _c_exfat.uint16 | None = ...,
            GeneralPrimaryFlags: _c_exfat.uint16 | None = ...,
            VolumeGuid: __cs__.Array[_c_exfat.uint8] | None = ...,
            Reserved: __cs__.Array[_c_exfat.uint8] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    VOLUME_GUID_DIRENT: TypeAlias = _VOLUME_GUID_DIRENT
    class _STREAM_EXT_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        GeneralSecondaryFlags: _c_exfat.uint8
        Reserved1: _c_exfat.uint8
        NameLength: _c_exfat.uint8
        NameHash: _c_exfat.uint16
        Reserved2: __cs__.Array[_c_exfat.uint8]
        ValidDataLength: _c_exfat.uint64
        Reserved3: __cs__.Array[_c_exfat.uint8]
        FirstCluster: _c_exfat.uint32
        DataLength: _c_exfat.uint64
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            GeneralSecondaryFlags: _c_exfat.uint8 | None = ...,
            Reserved1: _c_exfat.uint8 | None = ...,
            NameLength: _c_exfat.uint8 | None = ...,
            NameHash: _c_exfat.uint16 | None = ...,
            Reserved2: __cs__.Array[_c_exfat.uint8] | None = ...,
            ValidDataLength: _c_exfat.uint64 | None = ...,
            Reserved3: __cs__.Array[_c_exfat.uint8] | None = ...,
            FirstCluster: _c_exfat.uint32 | None = ...,
            DataLength: _c_exfat.uint64 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    STREAM_EXT_DIRENT: TypeAlias = _STREAM_EXT_DIRENT
    class _FILE_NAME_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        GeneralSecondaryFlags: _c_exfat.uint8
        FileName: __cs__.Array[_c_exfat.uint8]
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            GeneralSecondaryFlags: _c_exfat.uint8 | None = ...,
            FileName: __cs__.Array[_c_exfat.uint8] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    FILE_NAME_DIRENT: TypeAlias = _FILE_NAME_DIRENT
    class _VENDOR_EXT_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        GeneralSecondaryFlags: _c_exfat.uint8
        VendorGuid: __cs__.Array[_c_exfat.uint8]
        VendorDefined: __cs__.Array[_c_exfat.uint8]
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            GeneralSecondaryFlags: _c_exfat.uint8 | None = ...,
            VendorGuid: __cs__.Array[_c_exfat.uint8] | None = ...,
            VendorDefined: __cs__.Array[_c_exfat.uint8] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    VENDOR_EXT_DIRENT: TypeAlias = _VENDOR_EXT_DIRENT
    class _VENDOR_ALLOC_DIRENT(__cs__.Structure):
        EntryType: _c_exfat.uint8
        GeneralSecondaryFlags: _c_exfat.uint8
        VendorGuid: __cs__.Array[_c_exfat.uint8]
        VendorDefined: __cs__.Array[_c_exfat.uint8]
        FirstCluster: _c_exfat.uint32
        DataLength: _c_exfat.uint64
        @overload
        def __init__(
            self,
            EntryType: _c_exfat.uint8 | None = ...,
            GeneralSecondaryFlags: _c_exfat.uint8 | None = ...,
            VendorGuid: __cs__.Array[_c_exfat.uint8] | None = ...,
            VendorDefined: __cs__.Array[_c_exfat.uint8] | None = ...,
            FirstCluster: _c_exfat.uint32 | None = ...,
            DataLength: _c_exfat.uint64 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    VENDOR_ALLOC_DIRENT: TypeAlias = _VENDOR_ALLOC_DIRENT

# Technically `c_exfat` is an instance of `_c_exfat`, but then we can't use it in type hints
c_exfat: TypeAlias = _c_exfat

PRIMARY_DIRENT = (
    c_exfat.ALLOC_BITMAP_DIRENT
    | c_exfat.UPCASE_DIRENT
    | c_exfat.VOLUME_LABEL_DIRENT
    | c_exfat.FILE_DIRENT
    | c_exfat.VOLUME_GUID_DIRENT
    | c_exfat.GENERIC_PRIMARY_DIRENT
)
SECONDARY_DIRENT = (
    c_exfat.STREAM_EXT_DIRENT
    | c_exfat.FILE_NAME_DIRENT
    | c_exfat.VENDOR_EXT_DIRENT
    | c_exfat.VENDOR_ALLOC_DIRENT
    | c_exfat.GENERIC_SECONDARY_DIRENT
)
