# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_fat(__cs__.cstruct):
    ATTR_READ_ONLY: Literal[1] = ...
    ATTR_HIDDEN: Literal[2] = ...
    ATTR_SYSTEM: Literal[4] = ...
    ATTR_VOLUME_ID: Literal[8] = ...
    ATTR_DIRECTORY: Literal[16] = ...
    ATTR_ARCHIVE: Literal[32] = ...
    ATTR_LONG_NAME: Literal[15] = ...
    ATTR_LONG_NAME_MASK: Literal[63] = ...
    LAST_LONG_ENTRY: Literal[64] = ...
    class Fattype(__cs__.Enum):
        FATunknown = ...
        FAT12 = ...
        FAT16 = ...
        FAT32 = ...
        EXFAT = ...

    class Bpb(__cs__.Structure):
        BS_jmpBoot: __cs__.Array[_c_fat.uint8]
        BS_OEMName: __cs__.Array[_c_fat.uint8]
        BPB_BytsPerSec: _c_fat.uint16
        BPB_SecPerClus: _c_fat.uint8
        BPB_RsvdSecCnt: _c_fat.uint16
        BPB_NumFATs: _c_fat.uint8
        BPB_RootEntCnt: _c_fat.uint16
        BPB_TotSec16: _c_fat.uint16
        BPB_Media: _c_fat.uint8
        BPB_FATSz16: _c_fat.uint16
        BPB_SecPerTrk: _c_fat.uint16
        BPB_NumHeads: _c_fat.uint16
        BPB_HiddSec: _c_fat.uint32
        BPB_TotSec32: _c_fat.uint32
        @overload
        def __init__(
            self,
            BS_jmpBoot: __cs__.Array[_c_fat.uint8] | None = ...,
            BS_OEMName: __cs__.Array[_c_fat.uint8] | None = ...,
            BPB_BytsPerSec: _c_fat.uint16 | None = ...,
            BPB_SecPerClus: _c_fat.uint8 | None = ...,
            BPB_RsvdSecCnt: _c_fat.uint16 | None = ...,
            BPB_NumFATs: _c_fat.uint8 | None = ...,
            BPB_RootEntCnt: _c_fat.uint16 | None = ...,
            BPB_TotSec16: _c_fat.uint16 | None = ...,
            BPB_Media: _c_fat.uint8 | None = ...,
            BPB_FATSz16: _c_fat.uint16 | None = ...,
            BPB_SecPerTrk: _c_fat.uint16 | None = ...,
            BPB_NumHeads: _c_fat.uint16 | None = ...,
            BPB_HiddSec: _c_fat.uint32 | None = ...,
            BPB_TotSec32: _c_fat.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class Bpb16(__cs__.Structure):
        BS_DrvNum: _c_fat.uint8
        BS_Reserved1: _c_fat.uint8
        BS_BootSig: _c_fat.uint8
        BS_VolID: _c_fat.uint32
        BS_VolLab: __cs__.Array[_c_fat.uint8]
        BS_FilSysType: __cs__.Array[_c_fat.uint8]
        @overload
        def __init__(
            self,
            BS_DrvNum: _c_fat.uint8 | None = ...,
            BS_Reserved1: _c_fat.uint8 | None = ...,
            BS_BootSig: _c_fat.uint8 | None = ...,
            BS_VolID: _c_fat.uint32 | None = ...,
            BS_VolLab: __cs__.Array[_c_fat.uint8] | None = ...,
            BS_FilSysType: __cs__.Array[_c_fat.uint8] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class Bpb32(__cs__.Structure):
        BPB_FATSz32: _c_fat.uint32
        BPB_ExtFlags: _c_fat.uint16
        BPB_FSVer: _c_fat.uint16
        BPB_RootClus: _c_fat.uint32
        BPB_FSInfo: _c_fat.uint16
        BPB_BkBootSec: _c_fat.uint16
        BPB_Reserved: __cs__.Array[_c_fat.uint8]
        BS_DrvNum: _c_fat.uint8
        BS_Reserved1: _c_fat.uint8
        BS_BootSig: _c_fat.uint8
        BS_VolID: _c_fat.uint32
        BS_VolLab: __cs__.Array[_c_fat.uint8]
        BS_FilSysType: __cs__.Array[_c_fat.uint8]
        @overload
        def __init__(
            self,
            BPB_FATSz32: _c_fat.uint32 | None = ...,
            BPB_ExtFlags: _c_fat.uint16 | None = ...,
            BPB_FSVer: _c_fat.uint16 | None = ...,
            BPB_RootClus: _c_fat.uint32 | None = ...,
            BPB_FSInfo: _c_fat.uint16 | None = ...,
            BPB_BkBootSec: _c_fat.uint16 | None = ...,
            BPB_Reserved: __cs__.Array[_c_fat.uint8] | None = ...,
            BS_DrvNum: _c_fat.uint8 | None = ...,
            BS_Reserved1: _c_fat.uint8 | None = ...,
            BS_BootSig: _c_fat.uint8 | None = ...,
            BS_VolID: _c_fat.uint32 | None = ...,
            BS_VolLab: __cs__.Array[_c_fat.uint8] | None = ...,
            BS_FilSysType: __cs__.Array[_c_fat.uint8] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class Dirent(__cs__.Structure):
        DIR_Name: __cs__.Array[_c_fat.uint8]
        DIR_Attr: _c_fat.uint8
        DIR_NTRes: _c_fat.uint8
        DIR_CrtTimeTenth: _c_fat.uint8
        DIR_CrtTime: _c_fat.uint16
        DIR_CrtDate: _c_fat.uint16
        DIR_LstAccDate: _c_fat.uint16
        DIR_FstClusHI: _c_fat.uint16
        DIR_WrtTime: _c_fat.uint16
        DIR_WrtDate: _c_fat.uint16
        DIR_FstClusLO: _c_fat.uint16
        DIR_FileSize: _c_fat.uint32
        @overload
        def __init__(
            self,
            DIR_Name: __cs__.Array[_c_fat.uint8] | None = ...,
            DIR_Attr: _c_fat.uint8 | None = ...,
            DIR_NTRes: _c_fat.uint8 | None = ...,
            DIR_CrtTimeTenth: _c_fat.uint8 | None = ...,
            DIR_CrtTime: _c_fat.uint16 | None = ...,
            DIR_CrtDate: _c_fat.uint16 | None = ...,
            DIR_LstAccDate: _c_fat.uint16 | None = ...,
            DIR_FstClusHI: _c_fat.uint16 | None = ...,
            DIR_WrtTime: _c_fat.uint16 | None = ...,
            DIR_WrtDate: _c_fat.uint16 | None = ...,
            DIR_FstClusLO: _c_fat.uint16 | None = ...,
            DIR_FileSize: _c_fat.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class Ldirent(__cs__.Structure):
        LDIR_Ord: _c_fat.uint8
        LDIR_Name1: __cs__.Array[_c_fat.uint8]
        LDIR_Attr: _c_fat.uint8
        LDIR_Type: _c_fat.uint8
        LDIR_Chksum: _c_fat.uint8
        LDIR_Name2: __cs__.Array[_c_fat.uint8]
        LDIR_FstClusLO: _c_fat.uint16
        LDIR_Name3: __cs__.Array[_c_fat.uint8]
        @overload
        def __init__(
            self,
            LDIR_Ord: _c_fat.uint8 | None = ...,
            LDIR_Name1: __cs__.Array[_c_fat.uint8] | None = ...,
            LDIR_Attr: _c_fat.uint8 | None = ...,
            LDIR_Type: _c_fat.uint8 | None = ...,
            LDIR_Chksum: _c_fat.uint8 | None = ...,
            LDIR_Name2: __cs__.Array[_c_fat.uint8] | None = ...,
            LDIR_FstClusLO: _c_fat.uint16 | None = ...,
            LDIR_Name3: __cs__.Array[_c_fat.uint8] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_fat` is an instance of `_c_fat`, but then we can't use it in type hints
c_fat: TypeAlias = _c_fat
