# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_fatx(__cs__.cstruct):
    FAT_VOLUME_SIGNATURE: Literal[1481916742] = ...
    FAT_METADATA_BLOCK_SIZE: Literal[4096] = ...
    FAT_RESERVED_FAT_ENTRIES: Literal[1] = ...
    FAT_VOLUME_NAME_LENGTH: Literal[64] = ...
    FAT_ONLINE_DATA_LENGTH: Literal[2048] = ...
    FAT_DIRENT_NEVER_USED: Literal[0] = ...
    FAT_DIRENT_DELETED: Literal[229] = ...
    FAT_DIRENT_NEVER_USED2: Literal[255] = ...
    class _FAT_VOLUME_METADATA(__cs__.Structure):
        Signature: _c_fatx.uint32
        SerialNumber: _c_fatx.uint32
        SectorsPerCluster: _c_fatx.uint32
        RootDirFirstCluster: _c_fatx.uint32
        VolumeName: __cs__.Array[_c_fatx.uint8]
        OnlineData: __cs__.Array[_c_fatx.uint8]
        @overload
        def __init__(
            self,
            Signature: _c_fatx.uint32 | None = ...,
            SerialNumber: _c_fatx.uint32 | None = ...,
            SectorsPerCluster: _c_fatx.uint32 | None = ...,
            RootDirFirstCluster: _c_fatx.uint32 | None = ...,
            VolumeName: __cs__.Array[_c_fatx.uint8] | None = ...,
            OnlineData: __cs__.Array[_c_fatx.uint8] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    FAT_VOLUME_METADATA: TypeAlias = _FAT_VOLUME_METADATA
    class _DIRENT(__cs__.Structure):
        FileNameLength: _c_fatx.uint8
        FileAttributes: _c_fatx.uint8
        FileName: __cs__.Array[_c_fatx.uint8]
        FirstCluster: _c_fatx.uint32
        FileSize: _c_fatx.uint32
        CreationTime: _c_fatx.uint32
        LastWriteTime: _c_fatx.uint32
        LastAccessTime: _c_fatx.uint32
        @overload
        def __init__(
            self,
            FileNameLength: _c_fatx.uint8 | None = ...,
            FileAttributes: _c_fatx.uint8 | None = ...,
            FileName: __cs__.Array[_c_fatx.uint8] | None = ...,
            FirstCluster: _c_fatx.uint32 | None = ...,
            FileSize: _c_fatx.uint32 | None = ...,
            CreationTime: _c_fatx.uint32 | None = ...,
            LastWriteTime: _c_fatx.uint32 | None = ...,
            LastAccessTime: _c_fatx.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    DIRENT: TypeAlias = _DIRENT

# Technically `c_fatx` is an instance of `_c_fatx`, but then we can't use it in type hints
c_fatx: TypeAlias = _c_fatx
